### PR TITLE
Rebranding: CoW Protocol Explorer

### LINKED ISSUE #913: Rebranding: Update logo + title
**Description**

Update logo and title

cowProtocol-logo-preview

**Proposal**

New logo: (will attach to issue or link to source)
New title: CoW Protocol Explorer

Review texts throughout the app to update any mentions to Gnosis Protocol

**Additional context**

### PR DESCRIPTION
**Pull request by alongoni**
# Summary

Closes #913
image
## To Test
Go to [home](https://pr929--gpui.review.gnosisdev.com/)

### CODE REVIEW

**Comment by alongoni** [comment]
Just to be sure, should we have to replace all Gnosis Protocol references? Included the Gnosis Protocol v1 / v2 (e.g CoW Protocol v1)? 
image
@alfetopito @anxolin

**Comment by elena-zh** [comment]
Hey @alongoni , I think, it would be nicer if a CoW logo background will be transparent. WDYT?
image

**Comment by alongoni** [comment]
> Hey @alongoni , I think, it would be nicer if a CoW logo background will be transparent. WDYT? image

Hey @elena-zh Thanks! Yes, we can improve this. I've tried a simple solution using one favicon that works on both themes (dark and light).
image

**Comment by elena-zh** [comment]
@alongoni , got it!
So we can show the app logo for the dark mode as we currently show it for the CowSwap app: white cow icon without a bg circle
image

**Comment by alongoni** [comment]
favicon updated
image

**Review by matextrem — APPROVED** [review]

**Review by henrypalacios — APPROVED** [review]
Approved with just one comment!

What do you think about filling the cow with white?

This way on very dark tab backgrounds (like 3) it could be better appreciated.

**Comment by alfetopito** [comment]
Sorry Agustin, this is on my that failed to mention this in the issue.

Please add the word `explorer` to the logo, similar to what's in place already
Also, I think it would be good to give some space between the logo and the title

Screen Shot 2022-01-03 at 11 21 19

Screen Shot 2022-01-03 at 11 19 40

**Comment by alongoni** [comment]
> Sorry Agustin, this is my fault that failed to mention this in the issue.
> 
> Please add the word `explorer` to the logo, similar to what's in place already Also, I think it would be good to give some space between the logo and the title
> 
> Screen Shot 2022-01-03 at 11 21 19
> 
> Screen Shot 2022-01-03 at 11 19 40

Hey @alfetopito can you check it again? Thanks!!

**Review by alfetopito — APPROVED** [review]

**Comment by alfetopito** [comment]
I love it, good to go IMO.
I asked for team feedback but I'm happy to merge it in the mean time.

**Pull request merged**
