### PR TITLE
Release/2.5.0

### PR DESCRIPTION
**Pull request by henrypalacios**
# Release 2.5.0

:warning: DO NOT SQUASH :warning: 

**Main features**:
* Allow network switching through a menu in the header
* Improve user search experience
* Misc bug fixes and improvements

### Features
440788cc 917 rename xdai to gc (#918)
6f015160 Adding resolveENS function and use on UserDetail Page (#888)
ed26bc58 [Explorer] Networks change menu (#898)
c0c44a6f Retry endpoint when it does not return (#723)
bd1d8647 replaced placeholder with el (#880)
6620910e Explorer barn (#850)
d46940b5 Tooltips - increase tap area (#868)
e72bce00 Add SearchNotFound page (#828)
80ea6d8e Enable stale bot
e23e93d0 Signing status styles (#866)
e5b17876 Merge remote-tracking branch 'origin/release/2.4.0_update_develop' into develop
41b6c8cf Merge pull request #858 from gnosis/release/2.4.0

### Dependency updates
cf1e8c3e Bump date-fns from 2.26.0 to 2.27.0 (#907)
33f78817 Bump detect-browser from 5.2.1 to 5.3.0 (#893)
50bcf6ae Bump ethers from 5.5.1 to 5.5.2 (#892)
f77ac436 Bump @amcharts/amcharts4 from 4.10.22 to 4.10.23 (#879)
7002eeca Bump @popperjs/core from 2.10.2 to 2.11.0 (#877)
72593550 Bump @apollo/client from 3.5.4 to 3.5.5 (#878)
fb6e0fe3 Bump prettier from 2.4.1 to 2.5.0 (#872)
26a9144c Bump graphql from 15.6.1 to 15.7.2 (#805)
8f2053a5 Bump @apollo/client from 3.5.3 to 3.5.4 (#865)
6d2ba153 Bump date-fns from 2.25.0 to 2.26.0 (#864)
a0644e4b Bump eslint-plugin-react from 7.27.0 to 7.27.1 (#863)
011615ec Bump @types/node from 14.17.33 to 14.17.34 (#860)
459a4e04 Bump @apollo/client from 3.5.2 to 3.5.3 (#842)
a64fccde Bump @babel/preset-env from 7.16.0 to 7.16.4 (#841)
62083f28 Bump @sentry/tracing from 6.14.3 to 6.15.0 (#839)
b36e4c61 Bump @babel/plugin-transform-runtime from 7.16.0 to 7.16.4 (#840)
b4332944 Bump eslint-plugin-react-hooks from 4.2.0 to 4.3.0 (#837)
cc4f8117 Bump @types/react from 16.14.20 to 16.14.21 (#836)

### CODE REVIEW

**Review by alfetopito — COMMENTED** [review]
Found small bug on this screen
Screenshot from 2021-12-22 11-01-43

Check it out https://pr921--gpui.review.gnosisdev.com/gc/address/0x5B0ABE214aB7875562ADeE331dEfF0Fe1912FE42

`Ethereum` points to https://address/0x5B0ABE214aB7875562ADeE331dEfF0Fe1912FE42
`Rinkeby` points to the right url

Also, sometimes I see the image above for that address when looking at any network, but it has trades on all networks. Seems to be related to backend returning `504` sometimes, so no action on our side just yet for this.

Only thing that should be fixed is the path for Ethereum links

**Comment by elena-zh** [comment]
Changes in this PR LGTM. 
The issue mentioned above is fixed in #922 PR, and LGTM there.

**Review by alfetopito — APPROVED** [review]
:+1:

**Review by ramirotw — APPROVED** [review]
SoExcited~GIF

**Pull request merged**
