### PR TITLE
[Explorer] Remove 'This project is in beta. Use at your own risk' message in footer

### LINKED ISSUE #1035: Remove 'This project is in beta. Use at your own risk' message
Remove 'This project is in beta. Use at your own risk' message from the app footer

### PR DESCRIPTION
**Pull request by matextrem**
# Summary

Closes #1035 

Removed 'This project is in beta. Use at your own risk' message in footer

image

# To Test

1. Open any page. i.e: `Home`
    * You'll see the message 'This project is in beta. Use at your own risk' in footer has been removed.

### CODE REVIEW

**Review by alfetopito — COMMENTED** [review]
Not convinced we should remove the element completely while leaving behind the config

https://github.com/gnosis/gp-ui/blob/4d9e9b6022b9f67e36e5f1114ced73b3e73cf49e/src/components/layout/GenericLayout/Footer/config.ts#L2

Maybe we should just remove the flag || set `isBeta` to `false` by default in there?

**Comment by elena-zh** [comment]
@matextrem , LGTM from UI perspective, so I'm approving. 
But please address @alfetopito comments.

**Review by elena-zh — APPROVED** [review]

**Review by elena-zh — CHANGES_REQUESTED** [review]
Hey @matextrem , now the footer needs to be enhanced in a mobile/tablet resolution after the latest commit
image
image
image

**Review by alfetopito — APPROVED** [review]
👍 

Might just need to update how the component is rendered to avoid the issue Elena pointed out

**Review by alfetopito — APPROVED** [review]

**Comment by alfetopito** [comment]
Oh, it was merged onto the release branch, which is already live.

@matextrem please cherry-pick it onto `develop` otherwise it might be lost

**Comment by matextrem** [comment]
@alfetopito Done! https://github.com/gnosis/gp-ui/pull/1043

**Pull request merged**
