### PR TITLE
Validate if query isATxHash

### LINKED ISSUE #854: Implement search for transaction on search bar
Related to #780

Implement search for transaction on search bar: 
 - search TxHash by full match
 - add Tx Hash to the Main page name/placeholder in the search field 
 - add Tx Hash to the 'Not found' page name/placeholder in the search field

 - redirect to the 'Not found' page when no hash found

### PR DESCRIPTION
**Pull request by henrypalacios**
# Summary

Closes #854

**Proposal:**
Add search by Tx Hash:
- [x] search TxHash by full match.
- [x] add Tx Hash to the Main page name/placeholder in the search field.
- [x] add Tx Hash to the 'Not found' page name/placeholder in the search field.
- [x] redirect to the 'Not found' page when no hash found

## To Test:
1. Go to [home (PR-899)](https://pr899--gpui.review.gnosisdev.com/) page, search for **Tx hash** such as `0x98fa49ba5bd6a3ceb4fce7e26d19411b39c2772acafda09d5bf156b4813d73b0`

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @henrypalacios , I'm not sure if I need to test it, but I have taken a look into the PR and encountered several issues: 

1. Tx Hash is missing in placeholders in a mobile/tablet views on the Main and Search pages
mobile
mobile search

2. When I search for a not existing Tx Hash in a network, it blinks with the TX page first, then redirects to the Search page. It would be nice to replace this blink with a loader
https://watch.screencastify.com/v/Ql8YzvGuVcFx1i4pqahC

3. When I change a network in a transaction URL, it shows me first Search page, but then the app is reloaded and I'm redirected to the 404 page in the mainnet. Looks weird. 
https://watch.screencastify.com/v/yFe9WeQGFQW34A2ydKid 
 So I would redirect a user to the TX details page back as we do for an order details page.

Btw, please, do not forget to add me as a reviewer for the PRs you think I need to test/review. 
Thanks!

**Review by alfetopito — APPROVED** [review]
Looks good Henry.

One question though, should this PR handle the case when the TX is not "internal"?
For example, if I search for any random tx I get the not found page https://pr899--gpui.review.gnosisdev.com/search/0xe6f173ec21e32987b332c0291de9047415c665d497161d715cacb09e9b4922dc

**Comment by elena-zh** [comment]
Hey @henrypalacios !

Cases 1-2 I mentioned above LGTM, however, case 3 looks much better, but may be we could add a loader until the data is loading? 
https://watch.screencastify.com/v/RwGdFunvPFAr8pxpzn1E

**Comment by henrypalacios** [comment]
Great @elena-zh thanks for your feedback!

I have not been able to understand the requirement, do you mean that the header does not appear until the data is there?

Maybe working on it later when it joins with issue #882 and #856 would make more sense.

**Comment by elena-zh** [comment]
@henrypalacios , I just wanted to say that it would be nice to add a longer loader and remove these jumping/blinking effects while the data is being loaded. 
In the video [above ](https://watch.screencastify.com/v/RwGdFunvPFAr8pxpzn1E) you see: 
1. loader
2. then empty screen
3. then, finally, No results page. 
So it would be nice to replace all these actions by a loader until you get No results page

Anyways, I can create a separate issue for this. Please, let me know about it.

**Pull request merged**
