### PR TITLE
Update XDAI, WXDAI and GNO token logos

### LINKED ISSUE #942: Update logos for Gnosis chain according to the media-kit
https://github.com/gnosis/cowswap/pull/2023#issuecomment-1008832103

Additionally to the written name changes, can we also update the corresponding logos to this ones: https://www.xdaichain.com/media/media-kit

### PR DESCRIPTION
**Pull request by alongoni**
# Summary

Closes #942
After:
image
Before: 
image
 

# To Test
Compare the token logos and Gnosis Chain color on: 
✅ https://pr986--gpui.review.gnosisdev.com/gc/address/0xff714b8b0e2700303ec912bd40496c3997ceea2b
❌ https://protocol-explorer.dev.gnosisdev.com/gc/address/0xff714b8b0e2700303ec912bd40496c3997ceea2b

# Extra
Additionally out of 942 issue, I've added two minor CSS fixes:
- Invert arrow on network selector.
- Add more space between CoW Protocol Logo and the Network list.
Before    /    After
imageimage

GNO token logo added:
image

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]
😍

**Comment by elena-zh** [comment]
@alongoni , cool!
Just a nitpick: seems that the wxdai circle is not fixed in the center of the white bg icon circle. Look: 
image
image
image

The same is for xDAI
image
image

Anyways, we can go live with this issue. Please let me know If I need to open a low-low prio issue for this case.

**Review by elena-zh — APPROVED** [review]
Changes LGTM now!

**Review by henrypalacios — APPROVED** [review]
@elena-zh I was only able to reproduce this by increasing my browser's view resize to 125% and 175%. So I guess it might be a rendering issue.

- 100% 
Selection_424

- 125% 
Selection_423

**Pull request merged**
